export type Lang = "de" | "en";

const de = {
  switchLabel: "Switch to English",
  sendFail: "Die Nachricht konnte nicht gesendet werden.",
  nav: [["Dienstleistungen", "#dienstleistungen"], ["Über uns", "#team"], ["FAQ", "#faq"], ["Kontakt", "#kontakt"]] as [string, string][],
  toTop: "StartSaldo – zum Seitenanfang",
  cta: "Kontakt aufnehmen",
  menuOpen: "Menü öffnen",
  menuClose: "Menü schliessen",
  eyebrow: "Finanz- & Lohnbuchhaltung für Schweizer KMU",
  h1a: "Ihre Buchhaltung.",
  h1b: "Persönlich erledigt.",
  heroSub: "Wir übernehmen Ihre Finanz- und Lohnbuchhaltung zuverlässig und persönlich.",
  heroBtn1: "Unverbindliches Erstgespräch",
  heroBtn2: "Dienstleistungen ansehen",
  marqueeLabel: "Abstrakte Bilanz- und Erfolgsrechnungen in Bewegung",
  statementCards: [
    { title: "Bilanz", rows: ["Aktiven", "Umlaufvermögen", "Anlagevermögen", "Passiven"] },
    { title: "Erfolgsrechnung", rows: ["Betriebsertrag", "Personalaufwand", "Betriebsaufwand", "Ergebnis"] },
    { title: "Bilanz", rows: ["Flüssige Mittel", "Forderungen", "Eigenkapital", "Verbindlichkeiten"] },
    { title: "Erfolgsrechnung", rows: ["Nettoerlös", "Warenaufwand", "Betriebserfolg", "Jahresergebnis"] },
  ],
  svcEyebrow: "Unsere Dienstleistungen",
  svcTitle: "Was wir Ihnen abnehmen.",
  svcSub: "Von der laufenden Finanzbuchhaltung bis zur monatlichen Lohnadministration.",
  svcLink: "Jetzt Kontakt aufnehmen",
  fin: {
    title: "Finanzbuchhaltung",
    text: "Wir kümmern uns um Ihre laufende Buchhaltung von Belegen und Bankabstimmungen bis hin zur MWST-Abrechnung und Steuererklärung.",
    items: ["Laufende Erfassung Ihrer Geschäftsfälle", "Debitoren und Kreditoren", "Bank- und Kontenabstimmungen", "MWST-Abrechnungen und Vorbereitung der entsprechenden Unterlagen", "Monats-, Quartals- und Jahresabschlüsse", "Ausfüllung und Einreichung Ihrer Steuererklärung"],
  },
  pay: {
    title: "Lohnbuchhaltung",
    text: "Vom monatlichen Lohnlauf bis zum Lohnausweis und der Kommunikation mit der SVA: Wir kümmern uns um Ihre Lohnadministration.",
    items: ["Monatliche Lohnabrechnungen", "Ein- und Austritte von Mitarbeitenden", "Abrechnungen und Meldungen für die Ausgleichskasse", "Administration rund um die BVG und die UV", "Quellensteuer und entsprechende Meldungen", "Erstellung der jährlichen Lohnausweise", "Jahresenddeklarationen und Abstimmungen mit Versicherungen und Behörden", "Arbeitszeugnisse und andere Dokumente für Ihre Mitarbeiter"],
  },
  teamEyebrow: "Ihre Ansprechpartner",
  teamTitle: "Wer steht hinter den Zahlen?",
  teamSub: "Ihre Buchhaltung wird persönlich von uns betreut. So wissen Sie jederzeit, an wen Sie sich wenden können.",
  audelia: ["Finanzbuchhalterin", "Audelia betreut unsere Kunden in der Finanzbuchhaltung und sorgt dafür, dass Zahlen und Abstimmungen stimmen. Ihr ist wichtig, die Zusammenarbeit so einfach wie möglich zu gestalten mit klarer Kommunikation und unkomplizierten Lösungen für den Austausch von Dokumenten und Belegen."] as [string, string],
  sarah: ["Payroll Spezialistin | Sozialversicherungen", "Sarah ist vor allem für die Lohnbuchhaltung und Sozialversicherungen zuständig. Sie begleitet unsere Kunden vom monatlichen Lohnlauf bis zu Ein- und Austritten sowie Jahresendarbeiten."] as [string, string],
  portrait: "Portrait von",
  testiEyebrow: "Kundenfeedback",
  testiTitle: "Was unsere Kunden über die Zusammenarbeit sagen.",
  testiLabel: "Kundenfeedback – horizontal scrollbar",
  testimonials: [
    { quote: "«Die Buchhaltung meiner GmbH wird stets pünktlich und ordentlich erledigt. Ich bin mit der Kommunikation zufrieden und der Austausch mit Frau Sarah Mogel verläuft immer unkompliziert.»", name: "Jean-Marc Pittet" },
    { quote: "«Meine Buchhaltung wird zuverlässig und unkompliziert vorgenommen. Ich bin sehr dankbar für die Unterstützung und kann das Team sehr weiterempfehlen :)»", name: "Zita Varga", role: "Hundecoiffeursalon" },
  ] as { quote: string; name: string; role?: string }[],
  faqTitle: "Häufige Fragen.",
  faqSub: "Hier finden Sie Antworten zu Umfang, Zusammenarbeit und Einstieg.",
  faq: [
    ["Wie sieht eine Zusammenarbeit aus?", "1 Kennenlernen – Wir besprechen Ihr Unternehmen, Ihre aktuelle Situation und Ihren Bedarf.\n2 Zusammenarbeit definieren – Wir klären Aufgaben, Zuständigkeiten, Termine und Abläufe.\n3 Laufend betreuen – Wir übernehmen die vereinbarten Aufgaben zuverlässig und bleiben Ihre direkten Ansprechpartnerinnen."],
    ["Wo werden meine Daten gespeichert?", "Für den sicheren Austausch und die Speicherung von Dokumenten nutzen wir Proton. Die Daten werden Ende-zu-Ende verschlüsselt und auf Proton-Infrastruktur in der Schweiz bzw. Deutschland gespeichert."],
    ["Muss ich meine gesamte Buchhaltung auslagern?", "Nein. Sie können sowohl die gesamte Finanz- oder Lohnbuchhaltung als auch einzelne Aufgaben an uns übertragen. Gemeinsam definieren wir einen Umfang, der zu Ihrem Unternehmen und Ihren bestehenden Abläufen passt."],
    ["Können Sie mit meinem bestehenden Treuhänder zusammenarbeiten?", "Ja. Wir können die laufende Buchhaltung vorbereiten und mit Ihrem bestehenden Treuhänder oder Ihrer Revisionsstelle zusammenarbeiten. Die Zuständigkeiten stimmen wir zu Beginn klar miteinander ab."],
    ["Arbeiten Sie vollständig digital?", "Ja. Dokumente und Informationen können digital ausgetauscht werden. Dadurch bleiben die Abläufe effizient und Sie können unabhängig von Ihrem Standort mit uns zusammenarbeiten."],
    ["Für welche Unternehmen arbeiten Sie?", "Wir richten uns insbesondere an Schweizer KMU und junge Unternehmen, die ihre Finanz- und/oder Lohnbuchhaltung zuverlässig auslagern möchten."],
  ] as [string, string][],
  contactEyebrow: "Kontakt",
  contactTitle: "Nehmen Sie Kontakt mit uns auf.",
  phone: "Telefon",
  location: "Standort",
  locationValue: "Rothenthurm SZ, Schweiz",
  success: "Ihre Nachricht wurde erfolgreich versendet und so schnell wie möglich bearbeitet.",
  newMsg: "Neue Nachricht schreiben",
  fName: "Name",
  fCompany: "Firma",
  fMessage: "Nachricht",
  sending: "Wird gesendet…",
  submit: "Anfrage senden",
  consent: "Mit dem Absenden stimmen Sie der Bearbeitung Ihrer Angaben zur Kontaktaufnahme zu.",
  footerTag: "Finanz- & Lohnbuchhaltung für Schweizer KMU.",
  imprint: "Impressum",
  privacy: "Datenschutz",
};

const en: typeof de = {
  switchLabel: "Auf Deutsch wechseln",
  sendFail: "Your message could not be sent.",
  nav: [["Services", "#dienstleistungen"], ["About us", "#team"], ["FAQ", "#faq"], ["Contact", "#kontakt"]],
  toTop: "StartSaldo – back to top",
  cta: "Get in touch",
  menuOpen: "Open menu",
  menuClose: "Close menu",
  eyebrow: "Accounting & payroll for Swiss SMEs",
  h1a: "Your accounting.",
  h1b: "Handled personally.",
  heroSub: "We take care of your accounting and payroll – reliably and personally.",
  heroBtn1: "Free initial consultation",
  heroBtn2: "View services",
  marqueeLabel: "Abstract balance sheets and income statements in motion",
  statementCards: [
    { title: "Balance sheet", rows: ["Assets", "Current assets", "Fixed assets", "Liabilities"] },
    { title: "Income statement", rows: ["Operating income", "Personnel costs", "Operating costs", "Result"] },
    { title: "Balance sheet", rows: ["Cash", "Receivables", "Equity", "Payables"] },
    { title: "Income statement", rows: ["Net revenue", "Cost of goods", "Operating profit", "Net income"] },
  ],
  svcEyebrow: "Our services",
  svcTitle: "What we take off your hands.",
  svcSub: "From ongoing bookkeeping to monthly payroll administration.",
  svcLink: "Get in touch now",
  fin: {
    title: "Financial accounting",
    text: "We take care of your ongoing bookkeeping – from receipts and bank reconciliations to VAT returns and tax returns.",
    items: ["Ongoing recording of your business transactions", "Accounts receivable and payable", "Bank and account reconciliations", "VAT returns and preparation of the related documents", "Monthly, quarterly and annual closings", "Completion and filing of your tax return"],
  },
  pay: {
    title: "Payroll accounting",
    text: "From the monthly payroll run to salary certificates and communication with the social insurance office: we take care of your payroll administration.",
    items: ["Monthly payslips", "Employee onboarding and offboarding", "Statements and reports for the compensation fund (AHV)", "Administration of occupational pension (BVG) and accident insurance (UV)", "Withholding tax and related reports", "Preparation of annual salary certificates", "Year-end declarations and reconciliations with insurers and authorities", "Employment references and other documents for your staff"],
  },
  teamEyebrow: "Your contacts",
  teamTitle: "Who is behind the numbers?",
  teamSub: "Your accounting is handled personally by us. So you always know who to turn to.",
  audelia: ["Financial accountant", "Audelia supports our clients in financial accounting and makes sure figures and reconciliations are correct. She cares about keeping the collaboration as simple as possible, with clear communication and straightforward solutions for exchanging documents and receipts."],
  sarah: ["Payroll specialist | Social insurance", "Sarah is primarily responsible for payroll and social insurance. She supports our clients from the monthly payroll run to employee onboarding, offboarding and year-end work."],
  portrait: "Portrait of",
  testiEyebrow: "Client feedback",
  testiTitle: "What our clients say about working with us.",
  testiLabel: "Client feedback – horizontally scrollable",
  testimonials: [
    { quote: "“The accounting for my GmbH is always done punctually and properly. I am happy with the communication, and working with Ms Sarah Mogel is always straightforward.”", name: "Jean-Marc Pittet" },
    { quote: "“My accounting is handled reliably and without complications. I am very grateful for the support and can highly recommend the team :)”", name: "Zita Varga", role: "Dog grooming salon" },
  ],
  faqTitle: "Frequently asked questions.",
  faqSub: "Answers about scope, collaboration and getting started.",
  faq: [
    ["What does working together look like?", "1 Getting to know you – We discuss your company, your current situation and your needs.\n2 Defining the collaboration – We clarify tasks, responsibilities, deadlines and processes.\n3 Ongoing support – We reliably take care of the agreed tasks and remain your direct contacts."],
    ["Where is my data stored?", "We use Proton for the secure exchange and storage of documents. Data is end-to-end encrypted and stored on Proton infrastructure in Switzerland or Germany."],
    ["Do I have to outsource all of my accounting?", "No. You can hand over your entire financial or payroll accounting, or just individual tasks. Together we define a scope that fits your company and your existing processes."],
    ["Can you work with my existing fiduciary?", "Yes. We can prepare the ongoing accounting and work with your existing fiduciary or auditor. We clearly agree on responsibilities at the outset."],
    ["Do you work fully digitally?", "Yes. Documents and information can be exchanged digitally. This keeps processes efficient and lets you work with us wherever you are."],
    ["Which companies do you work for?", "We focus especially on Swiss SMEs and young companies that want to reliably outsource their financial and/or payroll accounting."],
  ],
  contactEyebrow: "Contact",
  contactTitle: "Get in touch with us.",
  phone: "Phone",
  location: "Location",
  locationValue: "Rothenthurm SZ, Switzerland",
  success: "Your message has been sent successfully and will be handled as soon as possible.",
  newMsg: "Write a new message",
  fName: "Name",
  fCompany: "Company",
  fMessage: "Message",
  sending: "Sending…",
  submit: "Send enquiry",
  consent: "By submitting, you agree to the processing of your details for the purpose of contacting you.",
  footerTag: "Accounting & payroll for Swiss SMEs.",
  imprint: "Legal notice",
  privacy: "Privacy",
};

export const copy = { de, en };
